/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trialproject;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard   
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_JPANEL = new javax.swing.JPanel();
        JP_Sideboard = new javax.swing.JPanel();
        JL_Navigation = new javax.swing.JLabel();
        JB_Dashboard = new javax.swing.JButton();
        JB_StatChart = new javax.swing.JButton();
        JL_Operations = new javax.swing.JLabel();
        JB_Expenses = new javax.swing.JButton();
        JB_SalesReport = new javax.swing.JButton();
        JB_Inventory = new javax.swing.JButton();
        JB_Menu = new javax.swing.JButton();
        JB_Waste = new javax.swing.JButton();
        JB_RestaurantSupplies = new javax.swing.JButton();
        JB_EquipmentExpenses = new javax.swing.JButton();
        JB_RentExpenses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_JPANEL.setBackground(new java.awt.Color(255, 164, 92));
        JP_JPANEL.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        JP_JPANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JP_JPANELMousePressed(evt);
            }
        });

        JP_Sideboard.setBackground(new java.awt.Color(93, 93, 90));

        JL_Navigation.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JL_Navigation.setForeground(new java.awt.Color(255, 255, 255));
        JL_Navigation.setText("Navigation");

        JB_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        JB_Dashboard.setText("Dashboard");
        JB_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DashboardActionPerformed(evt);
            }
        });

        JB_StatChart.setForeground(new java.awt.Color(255, 255, 255));
        JB_StatChart.setText("Statistics / Charts");

        JL_Operations.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JL_Operations.setForeground(new java.awt.Color(255, 255, 255));
        JL_Operations.setText("Reports");

        JB_Expenses.setForeground(new java.awt.Color(255, 255, 255));
        JB_Expenses.setText("Expenses Report");
        JB_Expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExpensesActionPerformed(evt);
            }
        });

        JB_SalesReport.setForeground(new java.awt.Color(255, 255, 255));
        JB_SalesReport.setText("Sales Report");
        JB_SalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalesReportActionPerformed(evt);
            }
        });

        JB_Inventory.setForeground(new java.awt.Color(255, 255, 255));
        JB_Inventory.setText("Inventory");

        JB_Menu.setForeground(new java.awt.Color(255, 255, 255));
        JB_Menu.setText("MENU");

        JB_Waste.setForeground(new java.awt.Color(255, 255, 255));
        JB_Waste.setText("Waste");

        JB_RestaurantSupplies.setForeground(new java.awt.Color(255, 255, 255));
        JB_RestaurantSupplies.setText("Restaurant Supplies");

        JB_EquipmentExpenses.setForeground(new java.awt.Color(255, 255, 255));
        JB_EquipmentExpenses.setText("Equipment Expenses");

        JB_RentExpenses.setForeground(new java.awt.Color(255, 255, 255));
        JB_RentExpenses.setText("Rent Exnpenses");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Miscellaneous");

        javax.swing.GroupLayout JP_SideboardLayout = new javax.swing.GroupLayout(JP_Sideboard);
        JP_Sideboard.setLayout(JP_SideboardLayout);
        JP_SideboardLayout.setHorizontalGroup(
            JP_SideboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JB_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_Inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_RentExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_EquipmentExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
            .addComponent(JL_Navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_StatChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JL_Operations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_SalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_Expenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_SideboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(JB_RestaurantSupplies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JB_Waste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JP_SideboardLayout.setVerticalGroup(
            JP_SideboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_SideboardLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(JL_Navigation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_StatChart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Operations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_SalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_RestaurantSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Waste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_EquipmentExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_RentExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout JP_JPANELLayout = new javax.swing.GroupLayout(JP_JPANEL);
        JP_JPANEL.setLayout(JP_JPANELLayout);
        JP_JPANELLayout.setHorizontalGroup(
            JP_JPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_JPANELLayout.createSequentialGroup()
                .addComponent(JP_Sideboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 901, Short.MAX_VALUE))
        );
        JP_JPANELLayout.setVerticalGroup(
            JP_JPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Sideboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(JP_JPANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JP_JPANELMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_JPANELMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JP_JPANELMousePressed

    private void JB_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_DashboardActionPerformed

    private void JB_ExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_ExpensesActionPerformed

    private void JB_SalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalesReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SalesReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Dashboard;
    private javax.swing.JButton JB_EquipmentExpenses;
    private javax.swing.JButton JB_Expenses;
    private javax.swing.JButton JB_Inventory;
    private javax.swing.JButton JB_Menu;
    private javax.swing.JButton JB_RentExpenses;
    private javax.swing.JButton JB_RestaurantSupplies;
    private javax.swing.JButton JB_SalesReport;
    private javax.swing.JButton JB_StatChart;
    private javax.swing.JButton JB_Waste;
    private javax.swing.JLabel JL_Navigation;
    private javax.swing.JLabel JL_Operations;
    private javax.swing.JPanel JP_JPANEL;
    private javax.swing.JPanel JP_Sideboard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
